upstream login-service {
    server login-service:80;
}

upstream payment-service {
    server payment-service:80;
}

upstream checkout-service {
    server checkout-service:80;
}

server {
    listen 80;

    location /login/ {
        proxy_pass http://login-service/;
    }

    location /payment/ {
        proxy_pass http://payment-service/;
    }

    location /checkout/ {
        proxy_pass http://checkout-service/;
    }
}
